[package]
name = "hello-me-desktop"
version = "0.1.1"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
anyhow = "1"
personal-studio = { path = ".." }
tauri = { version = "2", features = ["devtools"] }
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0.1"
